// <auto-generated />
namespace Parichay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_discountinsales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_discountinsales));
        
        string IMigrationMetadata.Id
        {
            get { return "202004120558082_added_discountinsales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
