// <auto-generated />
namespace Parichay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedTax_slab : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedTax_slab));
        
        string IMigrationMetadata.Id
        {
            get { return "202004060520469_addedTax_slab"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
