// <auto-generated />
namespace Parichay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_salesDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_salesDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202003290557582_added_salesDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
